### ISSUE TITLE
re-using client.producer from example code?

### ISSUE THREAD

**Issue by 1tylermitchell** [Jroland/kafka-net#35]
Hi, it's great to find this project.  I have been running it successfully but I am stuck, due to my poor C# knowledge and even poorer C# async understanding.  

Can you shed some light on how to maintain a single connection, but use `sendmessageasync` in a loop?  I've tried various combinations but get blocks or fails.  One error I get is below - any tips?

```
Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.ObjectDisposedException: The CancellationTokenSource has been disposed.
   at System.Threading.CancellationTokenSource.ThrowObjectDisposedException()
   at KafkaNet.KafkaTcpSocket.WriteAsync(Byte[] buffer)
   at KafkaNet.KafkaConnection.<SendAsync>d__0`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at KafkaNet.Producer.<SendMessageAsync>d__d.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at kafkatest1.Program.SendMessage(Producer client, String hostname)
   at kafkatest1.Program.Main(String[] args)
```

**Comment by Jroland** [comment]
I'm away until Tuesday but post your relevent code on how you are handling the producer or if you don't want it on here just email it to me directly. I'll have a look. The error above is a bit too generic but usually only happens when something is disposed. So my guess would be you are putting a using statement in too early. You want to keep a producer around for the life of the program.  I can be sure until I have a look at what you are doing.
